#!/bin/bash
export MSYS_NO_PATHCONV=1
export DOCKERHOST=${APPLICATION_URL-$(docker run --rm --net=host codenvy/che-ip)}
set -e

S2I_EXE=s2i
if [ -z $(type -P "$S2I_EXE") ]; then
  echo -e "The ${S2I_EXE} executable is needed and not on your path."
  echo -e "It can be downloaded from here: https://github.com/openshift/source-to-image/releases"
  echo -e "Make sure you extract the binary and place it in a directory on your path."
  exit 1
fi

SCRIPT_HOME="$(cd "$(dirname "$0")" && pwd)"

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage() {
  cat <<-EOF

      Usage: $0 [command] [options]

      Commands:

      up -  Builds the images, creates the application containers
            and starts the services based on the docker-compose.yml file.

            You can pass in a list of containers to start.
            By default all containers will be started.

            The API_URL used by tob-web can also be redirected.

            Examples:
            $0 start
            $0 start IDVERIFIER-agent

      start - Same as up

      restart - Re-starts the application containers,
                useful when updating one of the container images during development.

            You can pass in a list of containers to be restarted.
            By default all containers will be restarted.

            Examples:
            $0 start
            $0 start faber-agent

      logs - Display the logs from the docker compose run (ctrl-c to exit).

      stop - Stops the services.  This is a non-destructive process.  The volumes and containers
             are not deleted so they will be reused the next time you run start.

      down - Brings down the services and removes the volumes (storage) and containers.
      rm - Same as down


EOF
  exit 1
}
# -----------------------------------------------------------------------------------------------------------------
# Default Settings:
# -----------------------------------------------------------------------------------------------------------------
DEFAULT_CONTAINERS="ngrok-id-verifier id-verifier-agent id-verifier-notebook
                    ngrok-med-school medical-school-agent med-school-notebook
                    gmc-agent ngrok-gmc gmc-notebook
                    hee-agent ngrok-hee hee-notebook
                    lead-employer-agent ngrok-lead-employer lead-employer-notebook"

# -----------------------------------------------------------------------------------------------------------------
# Functions:
# -----------------------------------------------------------------------------------------------------------------
function echoRed() {
  _msg=${1}
  _red='\e[31m'
  _nc='\e[0m' # No Color
  echo -e "${_red}${_msg}${_nc}"
}

function echoYellow() {
  _msg=${1}
  _yellow='\e[33m'
  _nc='\e[0m' # No Color
  echo -e "${_yellow}${_msg}${_nc}"
}

configureEnvironment() {

  if [ -f .env ]; then
    while read line; do
      if [[ ! "$line" =~ ^\# ]] && [[ "$line" =~ .*= ]]; then
        export ${line//[$'\r\n']/}
      fi
    done <.env
  fi

  for arg in "$@"; do
    # Remove recognized arguments from the list after processing.
    shift

    # echo "arg: ${arg}"
    # echo "Remaining: ${@}"

    case "$arg" in
    *=*)
      # echo "Exporting ..."
      export "${arg}"
      ;;
    *)
      # echo "Saving for later ..."
      # If not recognized, save it for later procesing ...
      set -- "$@" "$arg"
      ;;
    esac
  done

  # global
  export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:controller}"
  export LEDGER_URL=${LEDGER_URL-http://$DOCKERHOST:9000}
  export WALLET_TYPE="indy"

  # IDVERIFIER-agent
  export IDVERIFIER_AGENT_NAME="ID Verification Service"
  export IDVERIFIER_ADMIN_PORT=8051
  export IDVERIFIER_HTTP_PORT=8050
  export IDVERIFIER_WEBHOOK_PORT=8052
  export IDVERIFIER_WEBHOOK_URL=${IDVERIFIER_WEBHOOK_URL:-http://$DOCKERHOST:$IDVERIFIER_WEBHOOK_PORT}
  export IDVERIFIER_AGENT_ENDPOINT=${IDVERIFIER_AGENT_ENDPOINT:-http://$DOCKERHOST:$IDVERIFIER_HTTP_PORT}
  export IDVERIFIER_WALLET_SEED="IDVERIFIER_seed_00000000000000000000000"
  export IDVERIFIER_JUPYTER_PORT="8889"


  # MEDICAL_SCHOOL-agent
  export MEDICAL_SCHOOL_AGENT_NAME="Medical School"
  export MEDICAL_SCHOOL_ADMIN_PORT=8021
  export MEDICAL_SCHOOL_HTTP_PORT=8020
  export MEDICAL_SCHOOL_WEBHOOK_PORT=8022
  export MEDICAL_SCHOOL_WEBHOOK_URL=${MEDICAL_SCHOOL_WEBHOOK_URL:-http://$DOCKERHOST:$MEDICAL_SCHOOL_WEBHOOK_PORT}
  export MEDICAL_SCHOOL_AGENT_ENDPOINT=${MEDICAL_SCHOOL_AGENT_ENDPOINT:-http://$DOCKERHOST:$MEDICAL_SCHOOL_HTTP_PORT}
  export MEDICAL_SCHOOL_WALLET_SEED="MEDICAL_SCHOOL_seed_000000000000000000000"
  export MEDICAL_SCHOOL_JUPYTER_PORT="8888"

  # GMC-agent
  export GMC_AGENT_NAME="General Medical Council"
  export GMC_ADMIN_PORT=8031
  export GMC_HTTP_PORT=8030
  export GMC_WEBHOOK_PORT=8032
  export GMC_WEBHOOK_URL=${GMC_WEBHOOK_URL:-http://$DOCKERHOST:$GMC_WEBHOOK_PORT}
  export GMC_AGENT_ENDPOINT=${GMC_AGENT_ENDPOINT:-http://$DOCKERHOST:$GMC_HTTP_PORT}
  export GMC_WALLET_SEED="GMC_seed_000000000000000000000123"
  export GMC_JUPYTER_PORT="8890"

  # HEE-agent
  export HEE_AGENT_NAME="Health Education England"
  export HEE_ADMIN_PORT=8041
  export HEE_HTTP_PORT=8040
  export HEE_WEBHOOK_PORT=8042
  export HEE_WEBHOOK_URL=${HEE_WEBHOOK_URL:-http://$DOCKERHOST:$HEE_WEBHOOK_PORT}
  export HEE_AGENT_ENDPOINT=${HEE_AGENT_ENDPOINT:-http://$DOCKERHOST:$HEE_HTTP_PORT}
  export HEE_WALLET_SEED="HEE_seed_000000000000000000000123"
  export HEE_JUPYTER_PORT="8891"

  # Lead Employer
  export LEAD_AGENT_NAME="NHS Lead Employer"
  export LEAD_ADMIN_PORT=8061
  export LEAD_HTTP_PORT=8060
  export LEAD_WEBHOOK_PORT=8062
  export LEAD_WEBHOOK_URL=${LEAD_WEBHOOK_URL:-http://$DOCKERHOST:$LEAD_WEBHOOK_PORT}
  export LEAD_AGENT_ENDPOINT=${LEAD_AGENT_ENDPOINT:-http://$DOCKERHOST:$LEAD_HTTP_PORT}
  export LEAD_WALLET_SEED="LEAD_seed_00000000000000000000012"
  export LEAD_JUPYTER_PORT="8892"






}

getInputParams() {
  ARGS=""

  for arg in $@; do
    case "$arg" in
    *=*)
      # Skip it
      ;;
    *)
      ARGS+=" $arg"
      ;;
    esac
  done

  echo ${ARGS}
}

getStartupParams() {
  CONTAINERS=""
  ARGS=""

  for arg in $@; do
    case "$arg" in
    *=*)
      # Skip it
      ;;
    -*)
      ARGS+=" $arg"
      ;;
    *)
      CONTAINERS+=" $arg"
      ;;
    esac
  done

  if [ -z "$CONTAINERS" ]; then
    CONTAINERS="$DEFAULT_CONTAINERS"
  fi

  echo ${ARGS} ${CONTAINERS}
}

deleteVolumes() {
  _projectName=${COMPOSE_PROJECT_NAME:-docker}

  echo "Stopping and removing any running containers ..."
  docker-compose down -v

  _pattern="^${_projectName}_\|^docker_"
  _volumes=$(docker volume ls -q | grep ${_pattern})

  if [ ! -z "${_volumes}" ]; then
    echo "Removing project volumes ..."
    echo ${_volumes} | xargs docker volume rm
  else
    echo "No project volumes exist."
  fi

  echo "Removing build cache ..."
  rm -Rf ../client/tob-web/.cache
}


getSeedJson() {
  _seed=${1}
  if [ -z "${_seed}" ]; then
    echo -e \\n"getSeedJson; Missing parameter!"\\n
    exit 1
  fi

  echo "{\"seed\": \"${_seed}\"}"
}

generateSeeds() {
  echo ${INDY_WALLET_SEED}
}



toLower() {
  echo $(echo ${@} | tr '[:upper:]' '[:lower:]')
}

echoError() {
  _msg=${1}
  _red='\033[0;31m'
  _nc='\033[0m' # No Color
  echo -e "${_red}${_msg}${_nc}" >&2
}

functionExists() {
  (
    if [ ! -z ${1} ] && type ${1} &>/dev/null; then
      return 0
    else
      return 1
    fi
  )
}
# =================================================================================================================

pushd "${SCRIPT_HOME}" >/dev/null
COMMAND=$(toLower ${1})
shift || COMMAND=usage

case "${COMMAND}" in
start | up)
  echoYellow "Starting up... This can take a couple of minutes."
  _startupParams=$(getStartupParams $@)
  configureEnvironment "$@"
  docker-compose\
  --log-level ERROR up \
  --build --remove-orphans \
  -d ${_startupParams}
  docker-compose \
  --log-level ERROR logs \
  -f
  ;;
restart)
  _startupParams=$(getStartupParams $@)
  configureEnvironment "$@"
  docker-compose stop ${_startupParams}
  docker-compose up -d --build --remove-orphans ${_startupParams}
  ;;
logs)
  configureEnvironment "$@"
  docker-compose logs -f
  ;;
stop)
  configureEnvironment
  docker-compose stop
  ;;
rm | down)
  configureEnvironment
  docker-compose \
  --log-level ERROR down \
  -v
  usage
  ;;
esac

popd >/dev/null
