# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class AdminAPIMessageTracing(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AdminAPIMessageTracing - a model defined in OpenAPI
        trace: Record trace information, based on agent configuration [Optional].
    """

    trace: Optional[bool] = None

    def __init__(
        self,
        *,
        trace: Optional[bool] = None,
        **kwargs,
    ):
        super().__init__(
            trace=trace,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


AdminAPIMessageTracing.update_forward_refs()
