# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class AdminStatusReadiness(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AdminStatusReadiness - a model defined in OpenAPI
        ready: Readiness status [Optional].
    """

    ready: Optional[bool] = None

    def __init__(
        self,
        *,
        ready: Optional[bool] = None,
        **kwargs,
    ):
        super().__init__(
            ready=ready,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


AdminStatusReadiness.update_forward_refs()
