# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class AttachmentDef(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AttachmentDef - a model defined in OpenAPI
        id: Attachment identifier [Optional].
        type: Attachment type [Optional].
    """

    id: Optional[str] = None
    type: Optional[Literal["credential-offer", "present-proof"]] = None

    def __init__(
        self,
        *,
        id: Optional[str] = None,
        type: Optional[Literal["credential-offer", "present-proof"]] = None,
        **kwargs,
    ):
        super().__init__(
            id=id,
            type=type,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


AttachmentDef.update_forward_refs()
