# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class ConnectionMetadataSetRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConnectionMetadataSetRequest - a model defined in OpenAPI
        metadata: Dictionary of metadata to set for connection..
    """

    metadata: Dict[str, Any]

    def __init__(
        self,
        *,
        metadata: Dict[str, Any] = None,
        **kwargs,
    ):
        super().__init__(
            metadata=metadata,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


ConnectionMetadataSetRequest.update_forward_refs()
