# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401
from aries_cloudcontroller.model.indy_cred_info import IndyCredInfo


class CredInfoList(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CredInfoList - a model defined in OpenAPI
        results: The results of this CredInfoList [Optional].
    """

    results: Optional[List[IndyCredInfo]] = None

    def __init__(
        self,
        *,
        results: Optional[List[IndyCredInfo]] = None,
        **kwargs,
    ):
        super().__init__(
            results=results,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


CredInfoList.update_forward_refs()
