# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class DIDCreateOptions(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DIDCreateOptions - a model defined in OpenAPI
        key_type: The key_type of this DIDCreateOptions.
    """

    key_type: Literal["ed25519", "bls12381g2"]

    def __init__(
        self,
        *,
        key_type: Literal["ed25519", "bls12381g2"] = None,
        **kwargs,
    ):
        super().__init__(
            key_type=key_type,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


DIDCreateOptions.update_forward_refs()
