# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401
from aries_cloudcontroller.model.did_create_options import DIDCreateOptions


class DIDCreate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DIDCreate - a model defined in OpenAPI
        method: The method of this DIDCreate [Optional].
        options: To define a key type for a did:key [Optional].
    """

    method: Optional[Literal["key", "sov"]] = None
    options: Optional[DIDCreateOptions] = None

    def __init__(
        self,
        *,
        method: Optional[Literal["key", "sov"]] = None,
        options: Optional[DIDCreateOptions] = None,
        **kwargs,
    ):
        super().__init__(
            method=method,
            options=options,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


DIDCreate.update_forward_refs()
