# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401
from aries_cloudcontroller.model.input_descriptors import InputDescriptors


class DIFProofProposal(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DIFProofProposal - a model defined in OpenAPI
        input_descriptors: The input_descriptors of this DIFProofProposal [Optional].
    """

    input_descriptors: Optional[List[InputDescriptors]] = None

    def __init__(
        self,
        *,
        input_descriptors: Optional[List[InputDescriptors]] = None,
        **kwargs,
    ):
        super().__init__(
            input_descriptors=input_descriptors,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


DIFProofProposal.update_forward_refs()
