# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class Disclosures(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Disclosures - a model defined in OpenAPI
        disclosures: List of protocol or goal_code descriptors.
        id: Message identifier [Optional].
        type: Message type [Optional].
    """

    disclosures: List[Dict]
    id: Optional[str] = Field(None, alias="@id")
    type: Optional[str] = Field(None, alias="@type")

    def __init__(
        self,
        *,
        disclosures: List[Dict] = None,
        id: Optional[str] = None,
        type: Optional[str] = None,
        **kwargs,
    ):
        super().__init__(
            id=id,
            type=type,
            disclosures=disclosures,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


Disclosures.update_forward_refs()
