# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class EndorserInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EndorserInfo - a model defined in OpenAPI
        endorser_did: Endorser DID.
        endorser_name: Endorser Name [Optional].
    """

    endorser_did: str
    endorser_name: Optional[str] = None

    def __init__(
        self,
        *,
        endorser_did: str = None,
        endorser_name: Optional[str] = None,
        **kwargs,
    ):
        super().__init__(
            endorser_did=endorser_did,
            endorser_name=endorser_name,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


EndorserInfo.update_forward_refs()
