# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class IndyProofProofAggregatedProof(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IndyProofProofAggregatedProof - a model defined in OpenAPI
        c_hash: c_hash value [Optional].
        c_list: c_list value [Optional].
    """

    c_hash: Optional[str] = None
    c_list: Optional[List[List[int]]] = None

    def __init__(
        self,
        *,
        c_hash: Optional[str] = None,
        c_list: Optional[List[List[int]]] = None,
        **kwargs,
    ):
        super().__init__(
            c_hash=c_hash,
            c_list=c_list,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


IndyProofProofAggregatedProof.update_forward_refs()
