# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401
from aries_cloudcontroller.model.raw_encoded import RawEncoded


class IndyProofRequestedProofRevealedAttrGroup(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IndyProofRequestedProofRevealedAttrGroup - a model defined in OpenAPI
        sub_proof_index: Sub-proof index [Optional].
        values: Indy proof requested proof revealed attr groups group value [Optional].
    """

    sub_proof_index: Optional[int] = None
    values: Optional[Dict[str, RawEncoded]] = None

    def __init__(
        self,
        *,
        sub_proof_index: Optional[int] = None,
        values: Optional[Dict[str, RawEncoded]] = None,
        **kwargs,
    ):
        super().__init__(
            sub_proof_index=sub_proof_index,
            values=values,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


IndyProofRequestedProofRevealedAttrGroup.update_forward_refs()
