# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401
from aries_cloudcontroller.model.indy_non_revoc_proof import IndyNonRevocProof
from aries_cloudcontroller.model.indy_primary_proof import IndyPrimaryProof


class IndyProofProofProofsProof(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IndyProofProofProofsProof - a model defined in OpenAPI
        non_revoc_proof: Indy non-revocation proof [Optional].
        primary_proof: Indy primary proof [Optional].
    """

    non_revoc_proof: Optional[IndyNonRevocProof] = None
    primary_proof: Optional[IndyPrimaryProof] = None

    def __init__(
        self,
        *,
        non_revoc_proof: Optional[IndyNonRevocProof] = None,
        primary_proof: Optional[IndyPrimaryProof] = None,
        **kwargs,
    ):
        super().__init__(
            non_revoc_proof=non_revoc_proof,
            primary_proof=primary_proof,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


IndyProofProofProofsProof.update_forward_refs()
