# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class KeylistQueryPaginate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    KeylistQueryPaginate - a model defined in OpenAPI
        limit: Limit for keylist query [Optional].
        offset: Offset value for query [Optional].
    """

    limit: Optional[int] = None
    offset: Optional[int] = None

    def __init__(
        self,
        *,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs,
    ):
        super().__init__(
            limit=limit,
            offset=offset,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


KeylistQueryPaginate.update_forward_refs()
