# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401
from aries_cloudcontroller.model.keylist_query_paginate import KeylistQueryPaginate


class KeylistQuery(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    KeylistQuery - a model defined in OpenAPI
        id: Message identifier [Optional].
        type: Message type [Optional].
        filter: Query dictionary object [Optional].
        paginate: Pagination info [Optional].
    """

    id: Optional[str] = Field(None, alias="@id")
    type: Optional[str] = Field(None, alias="@type")
    filter: Optional[Dict[str, Any]] = None
    paginate: Optional[KeylistQueryPaginate] = None

    def __init__(
        self,
        *,
        id: Optional[str] = None,
        type: Optional[str] = None,
        filter: Optional[Dict[str, Any]] = None,
        paginate: Optional[KeylistQueryPaginate] = None,
        **kwargs,
    ):
        super().__init__(
            id=id,
            type=type,
            filter=filter,
            paginate=paginate,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


KeylistQuery.update_forward_refs()
