# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class MediationDeny(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MediationDeny - a model defined in OpenAPI
        id: Message identifier [Optional].
        type: Message type [Optional].
        mediator_terms: The mediator_terms of this MediationDeny [Optional].
        recipient_terms: The recipient_terms of this MediationDeny [Optional].
    """

    id: Optional[str] = Field(None, alias="@id")
    type: Optional[str] = Field(None, alias="@type")
    mediator_terms: Optional[List[str]] = None
    recipient_terms: Optional[List[str]] = None

    def __init__(
        self,
        *,
        id: Optional[str] = None,
        type: Optional[str] = None,
        mediator_terms: Optional[List[str]] = None,
        recipient_terms: Optional[List[str]] = None,
        **kwargs,
    ):
        super().__init__(
            id=id,
            type=type,
            mediator_terms=mediator_terms,
            recipient_terms=recipient_terms,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


MediationDeny.update_forward_refs()
