# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class MediationCreateRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MediationCreateRequest - a model defined in OpenAPI
        mediator_terms: List of mediator rules for recipient [Optional].
        recipient_terms: List of recipient rules for mediation [Optional].
    """

    mediator_terms: Optional[List[str]] = None
    recipient_terms: Optional[List[str]] = None

    def __init__(
        self,
        *,
        mediator_terms: Optional[List[str]] = None,
        recipient_terms: Optional[List[str]] = None,
        **kwargs,
    ):
        super().__init__(
            mediator_terms=mediator_terms,
            recipient_terms=recipient_terms,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


MediationCreateRequest.update_forward_refs()
