# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401
from aries_cloudcontroller.model.menu_form_param import MenuFormParam


class MenuForm(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MenuForm - a model defined in OpenAPI
        description: Additional descriptive text for menu form [Optional].
        params: List of form parameters [Optional].
        submit_label: Alternative label for form submit button [Optional].
        title: Menu form title [Optional].
    """

    description: Optional[str] = None
    params: Optional[List[MenuFormParam]] = None
    submit_label: Optional[str] = Field(None, alias="submit-label")
    title: Optional[str] = None

    def __init__(
        self,
        *,
        description: Optional[str] = None,
        params: Optional[List[MenuFormParam]] = None,
        submit_label: Optional[str] = None,
        title: Optional[str] = None,
        **kwargs,
    ):
        super().__init__(
            description=description,
            params=params,
            submit_label=submit_label,
            title=title,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


MenuForm.update_forward_refs()
