# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class PerformRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PerformRequest - a model defined in OpenAPI
        name: Menu option name [Optional].
        params: Input parameter values [Optional].
    """

    name: Optional[str] = None
    params: Optional[Dict[str, str]] = None

    def __init__(
        self,
        *,
        name: Optional[str] = None,
        params: Optional[Dict[str, str]] = None,
        **kwargs,
    ):
        super().__init__(
            name=name,
            params=params,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


PerformRequest.update_forward_refs()
