# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class PingRequestResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PingRequestResponse - a model defined in OpenAPI
        thread_id: Thread ID of the ping message [Optional].
    """

    thread_id: Optional[str] = None

    def __init__(
        self,
        *,
        thread_id: Optional[str] = None,
        **kwargs,
    ):
        super().__init__(
            thread_id=thread_id,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


PingRequestResponse.update_forward_refs()
