# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class RegisterLedgerNymResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RegisterLedgerNymResponse - a model defined in OpenAPI
        success: Success of nym registration operation [Optional].
    """

    success: Optional[bool] = None

    def __init__(
        self,
        *,
        success: Optional[bool] = None,
        **kwargs,
    ):
        super().__init__(
            success=success,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


RegisterLedgerNymResponse.update_forward_refs()
