# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class SignResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SignResponse - a model defined in OpenAPI
        error: Error text [Optional].
        signed_doc: Signed document [Optional].
    """

    error: Optional[str] = None
    signed_doc: Optional[Dict[str, Any]] = None

    def __init__(
        self,
        *,
        error: Optional[str] = None,
        signed_doc: Optional[Dict[str, Any]] = None,
        **kwargs,
    ):
        super().__init__(
            error=error,
            signed_doc=signed_doc,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


SignResponse.update_forward_refs()
