# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class TAAAccept(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TAAAccept - a model defined in OpenAPI
        mechanism: The mechanism of this TAAAccept [Optional].
        text: The text of this TAAAccept [Optional].
        version: The version of this TAAAccept [Optional].
    """

    mechanism: Optional[str] = None
    text: Optional[str] = None
    version: Optional[str] = None

    def __init__(
        self,
        *,
        mechanism: Optional[str] = None,
        text: Optional[str] = None,
        version: Optional[str] = None,
        **kwargs,
    ):
        super().__init__(
            mechanism=mechanism,
            text=text,
            version=version,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


TAAAccept.update_forward_refs()
