# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class V10PresentationProblemReportRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V10PresentationProblemReportRequest - a model defined in OpenAPI
        description: The description of this V10PresentationProblemReportRequest.
    """

    description: str

    def __init__(
        self,
        *,
        description: str = None,
        **kwargs,
    ):
        super().__init__(
            description=description,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


V10PresentationProblemReportRequest.update_forward_refs()
