# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401


class V20CredRequestRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20CredRequestRequest - a model defined in OpenAPI
        holder_did: Holder DID to substitute for the credentialSubject.id [Optional].
    """

    holder_did: Optional[str] = None

    def __init__(
        self,
        *,
        holder_did: Optional[str] = None,
        **kwargs,
    ):
        super().__init__(
            holder_did=holder_did,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


V20CredRequestRequest.update_forward_refs()
