# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401
from aries_cloudcontroller.model.v20_cred_filter import V20CredFilter
from aries_cloudcontroller.model.v20_cred_preview import V20CredPreview


class V20CredBoundOfferRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20CredBoundOfferRequest - a model defined in OpenAPI
        counter_preview: Optional content for counter-proposal [Optional].
        filter: Credential specification criteria by format [Optional].
    """

    counter_preview: Optional[V20CredPreview] = None
    filter: Optional[V20CredFilter] = None

    def __init__(
        self,
        *,
        counter_preview: Optional[V20CredPreview] = None,
        filter: Optional[V20CredFilter] = None,
        **kwargs,
    ):
        super().__init__(
            counter_preview=counter_preview,
            filter=filter,
            **kwargs,
        )

    class Config:
        allow_population_by_field_name = True


V20CredBoundOfferRequest.update_forward_refs()
