FROM bcgovimages/von-image:py36-1.14-1

USER root
RUN apt-get update
RUN apt-get update && apt-get install -y gcc

ADD libs/attachment-protocol .


RUN pip3 install --no-cache-dir -e .
#
ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 ./jq
RUN chmod +x ./jq
COPY projects/iiw/startup.sh startup.sh
RUN chmod +x ./startup.sh
COPY projects/iiw/ngrok-wait.sh wait.sh
RUN chmod +x ./wait.sh

USER $user

CMD ./wait.sh ./startup.sh
