version: "3"
services:
  ngrok-agent:
    image: wernight/ngrok
    command: ngrok http agent:${AGENT_HTTP_PORT} --log stdout
    networks:
      - indy_demo
  agent:
    build:
      context: ../../
      dockerfile: dockerfiles/agents/Dockerfile.ngrok
    environment:
      - NGROK_NAME=ngrok-agent
      - ADMIN_URL=http://agent:${AGENT_ADMIN_PORT}
      - AGENT_NAME=${AGENT_NAME}
      - ADMIN_PORT=${AGENT_ADMIN_PORT}
      - HTTP_PORT=${AGENT_HTTP_PORT}
      - WEBHOOK_URL=${AGENT_WEBHOOK_URL}
      - AGENT_ENDPOINT=${AGENT_AGENT_ENDPOINT}
      - WALLET_SEED=${AGENT_WALLET_SEED}
      - WALLET_NAME=${AGENT_WALLET_NAME}
      - WALLET_TYPE=${WALLET_TYPE}
      - WALLET_KEY=${AGENT_WALLET_KEY}
      - ACAPY_ADMIN_INSECURE_MODE=true
      - GENESIS_URL=${GENESIS_URL}
    ports:
      - ${AGENT_HTTP_PORT}:${AGENT_HTTP_PORT}
      - ${AGENT_ADMIN_PORT}:${AGENT_ADMIN_PORT}
    networks:
      - indy_demo
    volumes:
      - agent:/home/indy/.indy_client/wallet
  controller-notebook:
    build:
      context: ../../
      dockerfile: dockerfiles/controllers/Dockerfile.attachmentcontroller
      args:
        - jupyter_port=${JUPYTER_PORT}
    depends_on:
      - agent
    networks:
      - indy_demo
    volumes:
      - ./notebooks:/workspace
    ports:
      - "8888:8888"
      - ${AGENT_WEBHOOK_PORT}:${AGENT_WEBHOOK_PORT}
volumes:
  agent:
networks:
  indy_demo:
