version: "3"
services:
  ngrok-dataowner:
    image: wernight/ngrok
    command: ngrok http dataowner-agent:3020 --log stdout
    env_file:
      - actors/dataowner/.env
    networks:
      - indy_demo
  dataowner-agent:
    build:
      context: ../../
      dockerfile: dockerfiles/agents/Dockerfile.ngrok-new
    env_file:
      - actors/dataowner/.env
    ports:
      - 5020:3020
      - 5021:3021
    networks:
      - indy_demo
  dataowner-business-logic:
    build:
      context: ../../
      dockerfile: dockerfiles/controllers/Dockerfile.basiccontroller
    env_file:
      - actors/dataowner/.env
    depends_on:
      - dataowner-agent
    networks:
      - indy_demo
    volumes:
      - ${PWD}/actors/dataowner/notebooks:/workspace
    ports:
      - "8889:8888"
      - 5010:3010
  om-authority-wallet-db:
    image: postgres:11
    container_name: om-authority-wallet-db
    command: postgres -c listen_addresses='*'
    env_file:
      - actors/om_authority/.env
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - indy_demo
    tty: true
  ngrok-om-authority:
    image: wernight/ngrok
    command: ngrok http om-authority-agent:3020 --log stdout
    env_file:
      - actors/om_authority/.env
    networks:
      - indy_demo
  om-authority-agent:
    build:
      context: ../../
      dockerfile: dockerfiles/agents/Dockerfile.ngrok-new
    env_file:
      - actors/om_authority/.env
    ports:
      - 3020:3020
      - 3021:3021
    depends_on:
      - om-authority-wallet-db
    networks:
      - indy_demo
  om-authority-business-logic:
    build:
      context: ../../
      dockerfile: dockerfiles/controllers/Dockerfile.basiccontroller
    env_file:
      - actors/om_authority/.env
    depends_on:
      - om-authority-agent
    networks:
      - indy_demo
    volumes:
      - ./actors/om_authority/notebooks:/workspace
    ports:
      - "8888:8888"
      - 3010:3010
  ngrok-datascientist:
    image: wernight/ngrok
    command: ngrok http datascientist-agent:3020 --log stdout
    env_file:
      - actors/datascientist/.env
    networks:
      - indy_demo
  datascientist-agent:
    build:
      context: ../../
      dockerfile: dockerfiles/agents/Dockerfile.ngrok-new
    env_file:
      - actors/datascientist/.env
    ports:
      # HTTP_PORT
      - 4020:3020
      # ADMIN_PORT
      - 4021:3021
    networks:
      - indy_demo
  datascientist-business-logic:
    build:
      context: ../../
      dockerfile: dockerfiles/controllers/Dockerfile.basiccontroller
    env_file:
      - actors/datascientist/.env
    depends_on:
      - datascientist-agent
    networks:
      - indy_demo
    volumes:
      - ./actors/datascientist/notebooks:/workspace
    ports:
      - "8890:8888"
      - 4010:3010

networks:
  indy_demo: