FROM bcgovimages/aries-cloudagent:py36-1.15-0_0.5.6

ADD configuration ./configuration

USER root

RUN pip3 install aries-cloudagent

ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 ./jq
RUN chmod +x ./jq
COPY scripts/startup.sh startup.sh
RUN chmod +x ./startup.sh
COPY scripts/ngrok-wait.sh wait.sh
RUN chmod +x ./wait.sh



USER $user


ENTRYPOINT  ["/usr/bin/env"]

CMD ./wait.sh ./startup.sh