FROM bcgovimages/aries-cloudagent:py36-1.15-0_0.5.6

ADD configuration ./configuration
ADD scripts ./scripts

USER root

ADD libs/attachment-protocol .


RUN pip3 install --no-cache-dir -e .
#
USER $user
