FROM bcgovimages/aries-cloudagent:py36-1.15-1_0.6.0

ADD configuration ./configuration
ADD scripts ./scripts

USER root

ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 ./jq
RUN chmod +x ./jq

RUN chmod +x ./scripts/startup-new.sh
RUN chmod +x ./scripts/ngrok-wait.sh

USER $user

ENTRYPOINT  ["/usr/bin/env"]
CMD ./scripts/ngrok-wait.sh ./scripts/startup-new.sh